import type { ShopMapPin } from "./types";
import { SHOP_CATEGORY_COLORS } from "./constants";

// Datos de demo para desarrollo — comercios ficticios en Madrid
export const DEMO_SHOPS: ShopMapPin[] = [
  {
    id: "1",
    name: "Panadería García",
    slug: "panaderia-garcia",
    logoUrl: null,
    categoryId: "alimentacion",
    categoryColor: SHOP_CATEGORY_COLORS.alimentacion,
    coordinates: { lat: 40.4168, lng: -3.7038 },
    distanceMeters: 120,
    rating: 4.8,
    isOpen: true,
  },
  {
    id: "2",
    name: "Moda Lucía",
    slug: "moda-lucia",
    logoUrl: null,
    categoryId: "moda",
    categoryColor: SHOP_CATEGORY_COLORS.moda,
    coordinates: { lat: 40.4195, lng: -3.7010 },
    distanceMeters: 380,
    rating: 4.5,
    isOpen: true,
  },
  {
    id: "3",
    name: "TechZone Madrid",
    slug: "techzone-madrid",
    logoUrl: null,
    categoryId: "electronica",
    categoryColor: SHOP_CATEGORY_COLORS.electronica,
    coordinates: { lat: 40.4140, lng: -3.7080 },
    distanceMeters: 620,
    rating: 4.2,
    isOpen: false,
  },
  {
    id: "4",
    name: "Cerámica Artesana",
    slug: "ceramica-artesana",
    logoUrl: null,
    categoryId: "artesania",
    categoryColor: SHOP_CATEGORY_COLORS.artesania,
    coordinates: { lat: 40.4210, lng: -3.6990 },
    distanceMeters: 850,
    rating: 5.0,
    isOpen: true,
  },
  {
    id: "5",
    name: "Frutería El Huerto",
    slug: "fruteria-el-huerto",
    logoUrl: null,
    categoryId: "alimentacion",
    categoryColor: SHOP_CATEGORY_COLORS.alimentacion,
    coordinates: { lat: 40.4155, lng: -3.7060 },
    distanceMeters: 200,
    rating: 4.7,
    isOpen: true,
  },
  {
    id: "6",
    name: "Deportes Cumbre",
    slug: "deportes-cumbre",
    logoUrl: null,
    categoryId: "deportes",
    categoryColor: SHOP_CATEGORY_COLORS.deportes,
    coordinates: { lat: 40.4180, lng: -3.7100 },
    distanceMeters: 450,
    rating: 4.3,
    isOpen: true,
  },
];
